name: workflow_to_trigger
on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Release version'     
        required: true
    
jobs:
  workflow_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version  }}
          release_name: ${{ github.event.inputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
