name: workflow_to_trigger
run-name: ${{ github.actor }} is testing triggers
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Log level'     
        required: true
        default: 'warning'
    
jobs:
  workflow_trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering wokflow"
      - run: echo ${{ fromJson(github.event.inputs.version) }}
      - name: Checkout
        uses: actions/checkout@v4
